# Generated by Django 6.1.1 on 2026-09-25 00:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_pics', models.ImageField(upload_to='users-profile-image/')),
                ('fullname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
