# Generated by Django 6.1.1 on 2026-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='users-profile-image/'),
        ),
    ]
